/**
 * Ownership classification for every file the documentation workspace
 * touches. This is the single source of truth for "may the system modify
 * this file automatically?".
 */
export type Ownership =
  /** A directory or file created and fully owned by the system. */
  | "system-managed"
  /** A file generated by the system that may be regenerated safely. */
  | "system-generated"
  /** A file authored by the user — never touched without explicit consent. */
  | "user-authored"
  /** A generated file the user has modified — never overwritten. */
  | "user-modified-generated"
  /** A file we cannot classify. */
  | "unknown";

/**
 * The plan action a path receives during initialization.
 */
export type InitAction =
  /** Create the path (it does not exist yet). */
  | "create"
  /** Leave the path untouched. */
  | "skip"
  /** Safe-merge content (e.g. managed skill sections). */
  | "merge"
  /** Update a system-managed path in place. */
  | "update"
  /** Surface a warning to the user. */
  | "warn"
  /** A genuine conflict requiring user attention. */
  | "conflict";

/** Risk level associated with a plan action. */
export type RiskLevel = "none" | "low" | "medium" | "high";

/** The kind of path a plan action targets. */
export type PathKind = "directory" | "file";

/** Map an ownership value to a human-readable label. */
export const OWNERSHIP_LABELS: Record<Ownership, string> = {
  "system-managed": "system managed",
  "system-generated": "system generated",
  "user-authored": "user authored",
  "user-modified-generated": "user modified generated",
  unknown: "unknown",
};

/**
 * A single step in the initialization plan.
 */
export interface PlanAction {
  /** Absolute path the action targets. */
  readonly path: string;
  /** The action to perform. */
  readonly action: InitAction;
  /** Human-readable justification. */
  readonly reason: string;
  /** Ownership classification of the target path. */
  readonly ownership: Ownership;
  /** Risk of the action. */
  readonly risk: RiskLevel;
  /** Whether the action requires explicit user confirmation. */
  readonly interactive: boolean;
  /** Whether the target is a directory or a file. */
  readonly kind: PathKind;
}
