import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary", "lcov", "html"],
      include: ["src/**/*.ts"],
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.spec.ts",
        "src/**/*.d.ts",
        "src/index.ts",
        "src/cli/index.ts",
        "src/types/index.ts",
        "src/types/internal.ts",
        "src/types/public.ts",
        "src/builders/index.ts",
        "src/config/index.ts",
        "src/config/types.ts",
        "src/constants/index.ts",
        "src/discovery/index.ts",
        "src/scanner/index.ts",
        "src/languages/index.ts",
        "src/features/index.ts",
        "src/utils/index.ts",
        "src/features/og.ts",
        "src/dev-server/index.ts",
        "src/components/index.ts",
        "src/themes/index.ts",
        "src/renderer/react.ts",
        "src/react.ts",
        "src/themes/types.ts",
        "src/engine/contracts/**",
        "src/compiler/index.ts",
        "src/symbols/index.ts",
        "src/references/index.ts",
        "src/graph/index.ts",
        "src/init/index.ts",
        "src/examples/index.ts",
        "src/documentation-relations/index.ts",
        "src/intelligence/index.ts",
        "src/state/index.ts",
        "src/renderers/index.ts",
        "src/templates/index.ts",
      ],
      thresholds: {
        statements: 90,
        branches: 75,
        functions: 90,
        lines: 90,
      },
    },
  },
});
