/**
 * Documentation Optimizer.
 *
 * Content fingerprinting and stability guarantees: every artifact's
 * fingerprint covers its inputs (evidence, plan, config, provider/model,
 * skill version) so unrelated source changes never invalidate pages.
 */

import { hashString } from "../../utils/hash.js";

/** Inputs that participate in an artifact fingerprint. */
export interface FingerprintInput {
  readonly pageSlug: string;
  readonly evidence: readonly string[];
  readonly planHash?: string;
  readonly configHash?: string;
  readonly providerId?: string;
  readonly modelId?: string;
  readonly skillVersion?: string;
}

/**
 * Compute a stable content fingerprint for a documentation artifact.
 * Only changes to the listed inputs change the fingerprint.
 */
export function computeFingerprint(input: FingerprintInput): string {
  const payload = JSON.stringify({
    slug: input.pageSlug,
    evidence: [...input.evidence].sort(),
    plan: input.planHash ?? "",
    config: input.configHash ?? "",
    provider: input.providerId ?? "deterministic",
    model: input.modelId ?? "",
    skill: input.skillVersion ?? "",
  });
  return hashString(payload);
}

/**
 * Decide whether a page must be regenerated by comparing fingerprints.
 */
export function needsRegeneration(
  storedFingerprint: string | undefined,
  currentFingerprint: string,
): boolean {
  return storedFingerprint !== currentFingerprint;
}

/**
 * Minimal-change selector: given previous and current page sets, return
 * only the slugs whose fingerprint (or existence) changed.
 */
export function selectChangedPages(
  previous: Readonly<Record<string, string>>,
  current: Readonly<Record<string, string>>,
): { regenerate: string[]; remove: string[] } {
  const regenerate: string[] = [];
  const remove: string[] = [];

  for (const [slug, fingerprint] of Object.entries(current)) {
    if (previous[slug] !== fingerprint) regenerate.push(slug);
  }
  for (const slug of Object.keys(previous)) {
    if (!(slug in current)) remove.push(slug);
  }

  return { regenerate: regenerate.sort(), remove: remove.sort() };
}
