/**
 * File Ownership Metadata (Phase 22).
 * Tracks whether a file is generated, user-authored, or customized.
 * Generated files carry a header `// generated by @vetwo/docs` to avoid overwriting user edits.
 */

export type FileOwnership = "generated" | "user" | "customized";

export const GENERATED_HEADER = "// generated by @vetwo/docs — do not edit";
export const GENERATED_HEADER_CSS = "/* generated by @vetwo/docs — do not edit */";
export const GENERATED_HEADER_HTML = "<!-- generated by @vetwo/docs — do not edit -->";

/**
 * Reports whether file content carries a generator ownership marker.
 *
 * @param content - File content to inspect.
 * @returns True when the content was written by the generator.
 */
export function isGenerated(content: string): boolean {
  return content.includes("generated by @vetwo/docs");
}

/**
 * Prepends the code-file generator ownership marker when absent.
 *
 * @param content - File content to mark.
 * @returns Content with the ownership marker.
 */
export function markGenerated(content: string): string {
  if (isGenerated(content)) return content;
  return `${GENERATED_HEADER}\n${content}`;
}

/** Format-appropriate marker chosen by file extension (CSS/HTML/MD need their own comment syntax). */
export function markGeneratedFor(path: string, contents: string): string {
  if (isGenerated(contents)) return contents;
  if (path.endsWith(".css")) return `${GENERATED_HEADER_CSS}\n${contents}`;
  if (path.endsWith(".html") || path.endsWith(".md") || path.endsWith(".mdx")) {
    return `${GENERATED_HEADER_HTML}\n${contents}`;
  }
  return markGenerated(contents);
}

/**
 * Decides whether new content may replace existing file content.
 *
 * @param existing - Current file content, if the file exists.
 * @returns True for new files and generator-owned files.
 */
export function shouldOverwrite(existing: string | undefined, _next: string): boolean {
  if (existing === undefined) return true;
  if (isGenerated(existing)) return true;
  // User-authored: preserve
  return false;
}
