export { emptyFileBindings } from "./binding.js";
export type {
  ReferenceExportBinding,
  ReferenceFileBindings,
  ReferenceImportBinding,
} from "./binding.js";
export {
  REFERENCE_DIAGNOSTIC_CODES,
  createReferenceDiagnostic,
  isErrorDiagnostic,
  type ReferenceDiagnostic,
  type ReferenceDiagnosticCode,
  type ReferenceDiagnosticInput,
  type ReferenceDiagnosticSeverity,
} from "./diagnostic.js";
export {
  DEPENDENCY_TYPES,
  REFERENCE_KINDS,
  REFERENCE_MODELS,
  createReference,
  isModuleReference,
  isReferenceKind,
  isResolvedReference,
  isUnresolvedReference,
  type AliasReference,
  type CallReference,
  type CircularReference,
  type CompositionReference,
  type ContainmentReference,
  type DependencyReference,
  type DependencyType,
  type ExportReference,
  type ExtendsReference,
  type ImportReference,
  type ImplementationReference,
  type ImplementsReference,
  type InheritanceReference,
  type ModuleReference,
  type OwnershipReference,
  type PackageReference,
  type Reference,
  type ReferenceInput,
  type ReferenceKind,
  type ReferenceModel,
  type ReferencePayload,
  type ReExportReference,
  type TypeReference,
  type UnknownReference,
  type UsesReference,
  type WorkspaceReference,
} from "./reference.js";
