import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { renderNextJsSite } from "./nextjs/adapter.js";
import { renderMarkdownSite } from "./markdown/renderer.js";
import { renderStaticSite } from "./static/renderer.js";
import { buildOutputPlan } from "./output-plan.js";
import { discoverImageSources } from "./assets.js";
import { assertRendererBoundary } from "../engine/docs-materialize.js";
import { IR_SCHEMA_VERSION, type DocumentationIR } from "../documentation/compiler/ir.js";

const here = dirname(fileURLToPath(import.meta.url));

function sampleIR(): DocumentationIR {
  const page = (slug: string) => ({
    slug,
    title: slug,
    sectionId: "s",
    description: `${slug} description`,
    blocks: [{ kind: "paragraph", text: `Body of ${slug}.` }],
    examples: [],
    claims: [],
    references: [{ sourcePage: slug, targetSlug: "introduction", relationship: "related" as const }],
    fingerprint: slug,
    provenance: "compiler" as const,
  });
  return {
    schemaVersion: IR_SCHEMA_VERSION,
    generatedAt: "2026-01-01",
    sections: [{ id: "s", title: "S", pageSlugs: ["introduction", "api/overview"] }],
    pages: [page("introduction"), page("api/overview")],
    navigation: {
      sidebar: [{ label: "S", children: [{ label: "I", slug: "introduction" }, { label: "A", slug: "api/overview" }] }],
      breadcrumbs: { introduction: [{ label: "I", slug: "introduction" }] },
    },
  } as unknown as DocumentationIR;
}

// Test 1+2: renderers cannot import source-analysis internals.
describe("renderer import boundary", () => {
  const FORBIDDEN = [
    "scanner",
    "intelligence",
    "api/analyzer",
    "api/models",
    "ProjectKnowledge",
    "createProgram",
    "references/",
    "graph/",
    "ai/",
  ];
  const MODULES = [
    "types.ts",
    "mdx.ts",
    "writer.ts",
    "output-plan.ts",
    "assets.ts",
    "markdown/renderer.ts",
    "static/renderer.ts",
    "nextjs/adapter.ts",
    "nextjs/manifest.ts",
    "nextjs/scaffold.ts",
  ];
  for (const mod of MODULES) {
    it(`${mod} imports no source-analysis internals`, () => {
      const src = readFileSync(join(here, mod), "utf8");
      // Strip comments so doc mentions don't trip the check.
      const code = src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|\s)\/\/.*$/gm, "");
      for (const bad of FORBIDDEN) {
        expect(code.includes(bad), `${mod} references forbidden module ${bad}`).toBe(false);
      }
    });
  }

  it("no renderer branches on specific project or page names", () => {
    const code = ["nextjs/adapter.ts", "nextjs/scaffold.ts", "markdown/renderer.ts", "static/renderer.ts"]
      .map((p) => readFileSync(join(here, p), "utf8"))
      .join("\n");
    // Attribution strings ("generated by @vetwo/docs", frontmatter generator
    // field) are required provenance, not behavior branches — only equality
    // branches against page slugs / project names are forbidden.
    for (const special of ['=== "introduction"', "=== 'introduction'", '=== "api"', "=== 'api'", '=== "quick-start"', "projectName ===", "project ==="]) {
      expect(code.includes(special)).toBe(false);
    }
  });
});

// Test 3: page JSON is serialized IR, not a second semantic model.
describe("page JSON is a transport of IR", () => {
  it("every payload mirrors its IR page exactly", () => {
    const ir = sampleIR();
    const site = renderNextJsSite(ir, { siteName: "T" });
    for (const page of ir.pages) {
      const file = site.files.find((f) => f.path === `data/pages/${encodeURIComponent(page.slug)}.json`)!;
      expect(file).toBeDefined();
      const data = JSON.parse(file.contents);
      expect(data.schemaVersion).toBe(IR_SCHEMA_VERSION);
      expect(data.slug).toBe(page.slug);
      expect(data.title).toBe(page.title);
      expect(data.blocks).toEqual(JSON.parse(JSON.stringify(page.blocks)));
    }
  });
});

// Test 4+5: navigation and search reference canonical page IDs.
describe("canonical page identity", () => {
  it("plan navigation slugs are all real IR pages", () => {
    const ir = sampleIR();
    const plan = buildOutputPlan(ir, { workspaceRoot: "/tmp" });
    const slugs = new Set(plan.pages.map((p) => p.slug));
    for (const node of plan.navigation) {
      if (node.slug !== undefined) expect(slugs.has(node.slug)).toBe(true);
      for (const child of node.children ?? []) {
        expect(child.slug !== undefined && slugs.has(child.slug)).toBe(true);
      }
    }
  });

  it("manifest routes and search-style urls resolve to planned pages", () => {
    const ir = sampleIR();
    const plan = buildOutputPlan(ir, { workspaceRoot: "/tmp" });
    for (const p of plan.pages) {
      expect(plan.pagesBySlug.get(p.slug)).toBeDefined();
      expect(p.route).toBe(`/docs/${p.slug}`);
    }
  });
});

// Test 6: assets have canonical IDs independent of renderer paths.
describe("asset identity", () => {
  it("local assets resolve per renderer without leaking absolute paths", () => {
    const plan = discoverImageSources(["logo.png", "https://cdn.example.com/a.png"], ["/proj"]);
    const local = plan.assets.find((a) => a.id === "logo.png")!;
    expect(local.missing).toBe(true); // fixture file does not exist
    expect(local.nextPath).not.toContain("/proj");
    expect(local.staticPath).not.toContain("/proj");
    expect(plan.missing).toContain("logo.png");
    const remote = plan.assets.find((a) => a.id.startsWith("https://"))!;
    expect(remote.missing).toBe(false);
  });
});

// Test 7: renderer paths derive from the output plan.
describe("output plan is the only path authority", () => {
  it("next/md/static paths match the plan", () => {
    const ir = sampleIR();
    const plan = buildOutputPlan(ir, { workspaceRoot: "/tmp" });
    const next = renderNextJsSite(ir, {});
    const md = renderMarkdownSite(ir, {});
    const statik = renderStaticSite(ir, {});
    for (const p of plan.pages) {
      expect(next.files.some((f) => f.path === `data/pages/${encodeURIComponent(p.slug)}.json`)).toBe(true);
      expect(md.files.some((f) => f.path === p.mdPath)).toBe(true);
      expect(statik.files.some((f) => f.path === p.staticPath)).toBe(true);
    }
  });
});

// Test 8: root enforcement.
describe("renderer root enforcement", () => {
  it("rejects escapes per renderer root", () => {
    const evil = { target: "nextjs", files: [{ path: "../md/evil.mdx", contents: "x" }], routes: [], entrypoint: "" } as const;
    const issues = assertRendererBoundary(evil as never, "/out/next");
    expect(issues.length).toBeGreaterThan(0);
    expect(issues[0]!.severity).toBe("error");
  });
});

// Test 9+10: CSS wiring on both targets.
describe("design system wiring", () => {
  it("next layout imports globals.css and the file ships tokens", () => {
    const ir = sampleIR();
    const site = renderNextJsSite(ir, {});
    const layout = site.files.find((f) => f.path === "app/layout.tsx")!.contents;
    expect(layout).toContain("globals.css");
    const css = site.files.find((f) => f.path === "app/globals.css")!.contents;
    expect(css).toContain("--vetwo-bg");
    expect(css).toContain(".vetwo-layout");
  });

  it("static pages reference a stylesheet that the static site ships", () => {
    const ir = sampleIR();
    const site = renderStaticSite(ir, {});
    const cssPaths = new Set(site.files.filter((f) => f.path.endsWith(".css")).map((f) => f.path));
    expect(cssPaths.size).toBeGreaterThan(0);
    for (const file of site.files.filter((f) => f.path.endsWith(".html"))) {
      const hrefs = [...file.contents.matchAll(/href="([^"]+\.css)"/g)].map((m) => m[1]!);
      expect(hrefs.length).toBeGreaterThan(0);
      for (const href of hrefs) {
        if (href.startsWith("http")) continue;
        // Resolve relative href against the page dir.
        const dir = file.path.split("/").slice(0, -1);
        const parts: string[] = [];
        for (const seg of [...dir, ...href.split("/")]) {
          if (seg === "..") parts.pop();
          else if (seg !== ".") parts.push(seg);
        }
        expect(cssPaths.has(parts.join("/"))).toBe(true);
      }
    }
  });
});

// Invariants across every planned page.
describe("page invariants", () => {
  it("ids/slugs/routes/paths are valid and unique", () => {
    const ir = sampleIR();
    const plan = buildOutputPlan(ir, { workspaceRoot: "/tmp" });
    const slugs = plan.pages.map((p) => p.slug);
    const routes = plan.pages.map((p) => p.route);
    const mdPaths = plan.pages.map((p) => p.mdPath);
    const staticPaths = plan.pages.map((p) => p.staticPath);
    for (const slug of slugs) {
      expect(slug.length).toBeGreaterThan(0);
      expect(slug).not.toContain("..");
    }
    expect(new Set(slugs).size).toBe(slugs.length);
    expect(new Set(routes).size).toBe(routes.length);
    expect(new Set(mdPaths).size).toBe(mdPaths.length);
    expect(new Set(staticPaths).size).toBe(staticPaths.length);
  });
});

export function __rendererDir(): string {
  return readdirSync(here).length > 0 ? here : here;
}
