/** Context used to render agent workspace README files. */
export interface AgentTemplateContext {
  readonly projectName: string;
  readonly skillPath: string;
  readonly outputDirectory: string;
}

/** Build the `agent/README.md` content. */
export function buildAgentReadme(ctx: AgentTemplateContext): string {
  return [
    `# ${ctx.projectName} — AI Documentation Agent Workspace`,
    "",
    "This directory is the dedicated workspace for the AI documentation agent.",
    "It is generated by `@vetwo/docs init` and is safe to regenerate: user-owned",
    "content is never overwritten.",
    "",
    "## Layout",
    "",
    "- `skill.md` — the canonical instruction file. **Read this first.**",
    "- `plans/` — documentation plans (brief, information architecture, page plan,",
    "  generation strategy, validation strategy).",
    "- `briefs/` — documentation planning artifacts (project brief, content plan,",
    "  page map).",
    "- `context/` — generated project intelligence snapshots.",
    "- `generated/` — AI-produced intermediate artifacts (summaries, guides,",
    "  examples, architecture).",
    "- `reports/` — analysis, validation, and generation reports.",
    "",
    "## The Skill File",
    "",
    `The \`${ctx.skillPath}\` file contains project-aware documentation instructions.`,
    "Sections marked with `<!-- vetwo:managed:start/end -->` are system-owned and",
    "may be updated by `docs init`; everything else belongs to you.",
    "",
    "## Generated vs. User Content",
    "",
    "- **System-generated** — `skill.md` (managed sections only), this README,",
    "  directory scaffolding. Safe to regenerate.",
    "- **User-authored** — everything you create in `plans/`, `briefs/`, `context/`,",
    "  `generated/`, and `reports/`, plus any edits you make. Never destroyed.",
    "",
    "## Workflow",
    "",
    "1. Read `skill.md` before starting.",
    "2. Draft a plan in `plans/` for significant work.",
    "3. Produce canonical documentation in the `md/` workspace under",
    `   \`${ctx.outputDirectory}/\`.`,
    "4. Keep intermediate artifacts in `generated/`.",
    "5. Write a validation report in `reports/` when done.",
    "",
    "## Customization",
    "",
    "Edit `skill.md` to change documentation behaviour. Keep the managed sections",
    "intact so upgrades can still update them. To disable the agent workspace,",
    "set `agent.enabled: false` in `docs.config.ts`.",
    "",
  ].join("\n");
}

/** Build the minimal `agent/plans/README.md` content. */
export function buildPlansReadme(): string {
  return [
    "# Documentation Plans",
    "",
    "Place documentation plans here:",
    "",
    "- `documentation-brief.md` — the overall documentation brief.",
    "- `information-architecture.md` — structure and navigation.",
    "- `page-plan.md` — the page-by-page plan.",
    "- `generation-strategy.md` — how content will be produced.",
    "- `validation-strategy.md` — how quality will be verified.",
    "",
    "Plans are user-owned content; the system never overwrites them.",
    "",
  ].join("\n");
}
