import type { InitLayout } from "../types/options.js";

/** Context used to render the generated `docs.config.ts`. */
export interface ConfigTemplateContext {
  readonly outputDirectory: string;
  readonly sourceDirectory: string;
  readonly layout: InitLayout;
  readonly agentEnabled: boolean;
  readonly skillPath: string;
}

/**
 * Builds the minimal, readable configuration file generated by `docs init`.
 *
 * Everything that can safely stay on defaults is left implicit — the file
 * only carries the content source, the output workspace, and the agent
 * workspace configuration.
 */
export function buildConfigContent(ctx: ConfigTemplateContext): string {
  const bool = (value: boolean): string => (value ? "true" : "false");
  const layoutEntries: string[] = [];
  if (ctx.layout.next) layoutEntries.push("      next: true,");
  if (ctx.layout.markdown) layoutEntries.push("      markdown: true,");
  if (ctx.layout.static) layoutEntries.push("      static: true,");
  const layoutBody =
    layoutEntries.length > 0 ? `\n    layout: {\n${layoutEntries.join("\n")}\n    },` : "";
  const sourceLine = ctx.layout.markdown
    ? `  source: ${JSON.stringify(ctx.sourceDirectory)},`
    : `  source: ${JSON.stringify(ctx.outputDirectory)},`;

  return [
    'import { defineDocs } from "@vetwo/docs";',
    "",
    "export default defineDocs({",
    sourceLine,
    "  output: {",
    `    directory: ${JSON.stringify(ctx.outputDirectory)},`,
    layoutBody,
    "  },",
    "  agent: {",
    `    enabled: ${bool(ctx.agentEnabled)},`,
    "    skill: {",
    `      path: ${JSON.stringify(ctx.skillPath)},`,
    "    },",
    "  },",
    "});",
    "",
  ].join("\n");
}
