import { SKILL_SCHEMA_VERSION } from "../types/manifest.js";

/** The identifier used in the skill frontmatter. */
export const SKILL_ID = "vetwo-docs";

/** Marker prefix used to delimit system-managed skill sections. */
export const MANAGED_START = "vetwo:managed:start";

/** Marker prefix used to close system-managed skill sections. */
export const MANAGED_END = "vetwo:managed:end";

/** System-managed skill section names. Only these may be updated automatically. */
export const MANAGED_SECTIONS = ["project-context", "output-layout"] as const;

export type ManagedSection = (typeof MANAGED_SECTIONS)[number];

/** Context used to render the project-aware skill template. */
export interface SkillContext {
  readonly projectName: string;
  readonly projectDescription: string;
  readonly projectType: string;
  readonly packageManager: string;
  readonly packages: readonly { readonly name: string; readonly description?: string }[];
  readonly outputDirectory: string;
  readonly skillPath: string;
  readonly generatedAt: string;
  readonly version?: number;
}

/** Build the YAML-ish frontmatter block for a skill file. */
export function buildSkillFrontmatter(ctx: SkillContext): string {
  const version = ctx.version ?? SKILL_SCHEMA_VERSION;
  return [
    "---",
    `skill: ${SKILL_ID}`,
    `version: ${version}`,
    'generatedBy: "@vetwo/docs"',
    `generatedAt: ${ctx.generatedAt}`,
    `project: ${jsonString(ctx.projectName)}`,
    "---",
  ].join("\n");
}

/** Wrap a body in the managed-section markers. */
export function managedSection(name: ManagedSection, body: string): string {
  return [`<!-- ${MANAGED_START} ${name} -->`, body.trim(), `<!-- ${MANAGED_END} ${name} -->`].join(
    "\n\n",
  );
}

function jsonString(value: string): string {
  return /^[A-Za-z0-9 ._/-]+$/.test(value) ? value : JSON.stringify(value);
}

/** Build the project-context managed section. */
function projectContext(ctx: SkillContext): string {
  const packages =
    ctx.packages.length > 0
      ? ctx.packages
          .map((p) => `- ${p.name}${p.description ? ` — ${p.description}` : ""}`)
          .join("\n")
      : "- (no packages detected)";
  return [
    "The project this documentation describes:",
    "",
    `- Project: ${ctx.projectName}`,
    `- Type: ${ctx.projectType}`,
    `- Package manager: ${ctx.packageManager}`,
    `- Description: ${ctx.projectDescription || "(none provided)"}`,
    "",
    "Detected packages:",
    packages,
  ].join("\n");
}

/** Build the output-layout managed section. */
function outputLayout(ctx: SkillContext): string {
  return [
    "The documentation workspace lives under:",
    "",
    `- Output root: \`${ctx.outputDirectory}/\``,
    "- `next/` — Next.js documentation application workspace",
    "- `md/` — canonical Markdown/MDX documentation content",
    "- `static/` — generated static output (do not hand-edit)",
    "",
    `Always write canonical documentation content into the Markdown workspace unless a task explicitly targets the Next.js application.`,
  ].join("\n");
}

/**
 * Builds the complete project-aware `skill.md` content.
 *
 * System-managed sections are delimited by explicit markers so a future
 * `docs init` / `docs upgrade` can update them without touching user content.
 */
export function buildSkillContent(ctx: SkillContext): string {
  return [
    buildSkillFrontmatter(ctx),
    "",
    `# ${ctx.projectName} — Documentation Skill`,
    "",
    "> Read this file before starting any documentation work for this project.",
    "",
    "## Purpose",
    "",
    "This skill file instructs the AI documentation agent how to produce, maintain,",
    "and validate documentation for the detected project. It is generated by",
    "`@vetwo/docs init` and is safe to regenerate: sections owned by the system are",
    "marked explicitly and everything else is preserved.",
    "",
    "## Before You Start",
    "",
    "1. Read `agent/README.md` for the agent workspace layout.",
    "2. Read the project-context section below for what this project is.",
    "3. Read the output-layout section below for where documentation must land.",
    "4. Never edit files in `static/` — it is generated output.",
    "",
    "## Documentation Workflow",
    "",
    "1. Inspect the existing documentation before generating anything new.",
    "2. Reuse existing structure and conventions; extend, do not duplicate.",
    "3. Write canonical content as Markdown/MDX into the Markdown workspace.",
    "4. Keep generated artifacts in `agent/generated/` until they are final.",
    "5. Validate every page: links resolve, code examples run, metadata is present.",
    "6. Record progress in `agent/reports/`.",
    "",
    "## Rules",
    "",
    "- Never destroy existing user-authored content.",
    "- Never place final site output in `agent/`.",
    "- Prefer small, focused pages over monolithic documents.",
    "- Use consistent heading structure (`#` per page, `##` per section).",
    "- Include a table of contents for pages longer than ~300 words.",
    "- Keep code samples runnable and complete.",
    "",
    managedSection("project-context", projectContext(ctx)),
    "",
    managedSection("output-layout", outputLayout(ctx)),
    "",
    "## Validation",
    "",
    "Before reporting a documentation task complete, verify:",
    "",
    "- All internal links resolve.",
    "- Every page has a title and description in its frontmatter.",
    "- Code blocks are syntactically valid.",
    "- The documentation reflects the current state of the project.",
    "",
  ].join("\n");
}

/**
 * Extracts the managed sections present in a skill file, keyed by section name.
 * Unrecognised or malformed markers are ignored.
 */
export function extractManagedSections(content: string): ReadonlyMap<ManagedSection, string> {
  const result = new Map<ManagedSection, string>();
  for (const name of MANAGED_SECTIONS) {
    const start = content.indexOf(`<!-- ${MANAGED_START} ${name} -->`);
    const end = content.indexOf(`<!-- ${MANAGED_END} ${name} -->`);
    if (start !== -1 && end !== -1 && end > start) {
      const body = content.slice(start + `<!-- ${MANAGED_START} ${name} -->`.length, end).trim();
      result.set(name, body);
    }
  }
  return result;
}

/** Whether a skill file contains any system-managed section markers. */
export function hasManagedSections(content: string): boolean {
  return content.includes(MANAGED_START) && content.includes(MANAGED_END);
}
