import type { Plugin } from "@vetwo/docs";

export interface MyPluginOptions {
  prefix?: string;
}

/**
 * A custom plugin that demonstrates the @vetwo/docs plugin API.
 *
 * This plugin hooks into multiple lifecycle stages to log information
 * and transform documentation content during the build process.
 */
export function myPlugin(options: MyPluginOptions = {}): Plugin {
  const prefix = options.prefix ?? "my-plugin";

  return {
    name: "example/my-plugin",
    version: "0.1.0",

    hooks: {
      init(ctx) {
        ctx.log.info(`[${prefix}] Build initialized`);
      },

      discover(ctx) {
        const fileCount = ctx.ctx.sourceFiles.length;
        ctx.log.info(`[${prefix}] Discovered ${fileCount} source files`);
      },

      load(ctx) {
        const pageCount = ctx.ctx.pages.length;
        ctx.log.info(`[${prefix}] Loaded ${pageCount} doc pages`);
      },

      transform(ctx) {
        ctx.ctx.pages = ctx.ctx.pages.map((page) => ({
          ...page,
          content: `<!-- Generated by ${prefix} -->\n\n${page.content}`,
        }));
        ctx.log.info(`[${prefix}] Transformed ${ctx.ctx.pages.length} pages`);
      },

      generate(ctx) {
        ctx.log.info(`[${prefix}] Generating output`);
        ctx.log.table(
          ["Metric", "Value"],
          [
            ["Pages", String(ctx.ctx.pages.length)],
            ["API Docs", String(ctx.ctx.apiDocs.length)],
            ["Sitemap Entries", String(ctx.ctx.sitemapEntries.length)],
          ],
        );
      },

      done(ctx) {
        const duration = ((Date.now() - ctx.ctx.startTime) / 1000).toFixed(2);
        ctx.log.success(`[${prefix}] Build completed in ${duration}s`);
      },
    },
  };
}
