import React from "react";

/** Props for the DocsLayout component */
export interface DocsLayoutProps {
  readonly title: string;
  readonly description?: string;
  readonly nav?: readonly { label: string; href: string }[];
  readonly sidebar?: readonly {
    readonly title: string;
    readonly items: readonly { label: string; href: string }[];
  }[];
  readonly children: React.ReactNode;
  readonly theme?: "light" | "dark" | "system";
}

/**
 * Main documentation layout component.
 * Wraps page content with header, sidebar, and footer.
 */
export function DocsLayout({
  title,
  description,
  nav,
  sidebar,
  children,
  theme,
}: DocsLayoutProps): React.JSX.Element {
  const themeAttr = theme ? { "data-theme": theme } : {};
  return React.createElement(
    "div",
    { className: "vetwo-docs-layout", ...themeAttr },
    React.createElement(
      "header",
      { className: "vetwo-header" },
      React.createElement(
        "div",
        { className: "vetwo-header-inner" },
        React.createElement("a", { href: "/", className: "vetwo-brand" }, title),
        description
          ? React.createElement("span", { className: "vetwo-description" }, description)
          : null,
        nav
          ? React.createElement(
              "nav",
              { className: "vetwo-nav" },
              ...nav.map((item) =>
                React.createElement("a", { key: item.href, href: item.href }, item.label),
              ),
            )
          : null,
      ),
    ),
    React.createElement(
      "div",
      { className: "vetwo-body" },
      sidebar && sidebar.length > 0
        ? React.createElement(
            "aside",
            { className: "vetwo-sidebar" },
            ...sidebar.map((group) =>
              React.createElement(
                "div",
                { key: group.title, className: "vetwo-sidebar-group" },
                React.createElement("h3", null, group.title),
                React.createElement(
                  "ul",
                  null,
                  ...group.items.map((item) =>
                    React.createElement(
                      "li",
                      { key: item.href },
                      React.createElement("a", { href: item.href }, item.label),
                    ),
                  ),
                ),
              ),
            ),
          )
        : null,
      React.createElement("main", { className: "vetwo-content" }, children),
    ),
    React.createElement(
      "footer",
      { className: "vetwo-footer" },
      React.createElement(
        "p",
        null,
        "Generated by ",
        React.createElement("a", { href: "https://github.com/vetwo/docs" }, "@vetwo/docs"),
      ),
    ),
  );
}

/** Props for the MarkdownRenderer component */
export interface MarkdownRendererProps {
  readonly content: string;
  readonly className?: string;
}

/**
 * Renders pre-processed HTML markdown content.
 * The HTML is generated by the @vetwo/docs pipeline.
 */
export function MarkdownRenderer({ content, className }: MarkdownRendererProps): React.JSX.Element {
  return React.createElement("article", {
    className: className ?? "vetwo-markdown",
    dangerouslySetInnerHTML: { __html: content },
  });
}

/** Props for the TOC component */
export interface TOCProps {
  readonly headings: readonly {
    level: number;
    id: string;
    text: string;
  }[];
  readonly maxDepth?: number;
}

/**
 * Renders a table of contents from extracted headings.
 */
export function TOC({ headings, maxDepth = 3 }: TOCProps): React.JSX.Element | null {
  const filtered = headings.filter((h) => h.level >= 2 && h.level <= maxDepth);
  if (filtered.length === 0) return null;

  return React.createElement(
    "nav",
    { className: "vetwo-toc", "aria-label": "Table of Contents" },
    React.createElement("h2", null, "On This Page"),
    React.createElement(
      "ul",
      null,
      ...filtered.map((h) =>
        React.createElement(
          "li",
          { key: h.id },
          React.createElement("a", { href: `#${h.id}` }, h.text),
        ),
      ),
    ),
  );
}

/** Props for the ThemeToggle component */
export interface ThemeToggleProps {
  readonly defaultTheme?: "light" | "dark";
}

/**
 * Client-side theme toggle button.
 * Use in a React Client Component with "use client" directive.
 */
export function ThemeToggle({ defaultTheme = "light" }: ThemeToggleProps): React.JSX.Element {
  return React.createElement(
    "button",
    {
      className: "vetwo-theme-toggle",
      "aria-label": "Toggle dark mode",
      suppressHydrationWarning: true,
    },
    defaultTheme === "dark" ? "🌙" : "☀️",
  );
}

/** Props for the SearchBox component */
export interface SearchBoxProps {
  readonly searchUrl?: string;
  readonly placeholder?: string;
}

/**
 * Search box component that links to the search page.
 */
export function SearchBox({
  searchUrl = "/search",
  placeholder = "Search...",
}: SearchBoxProps): React.JSX.Element {
  return React.createElement(
    "div",
    { className: "vetwo-search" },
    React.createElement(
      "a",
      { href: searchUrl, className: "vetwo-search-link" },
      React.createElement("input", {
        type: "text",
        placeholder,
        readOnly: true,
        className: "vetwo-search-input",
      }),
    ),
  );
}
